### ISSUE TITLE
Some advice please :)

### ISSUE THREAD

**Issue by PandoraSec** [4w4k3/Umbrella#2]
hi, i start to use Umbrella, and i embed paylaods in docs and jpg, but i dont figure out how to use with phishing, and how to download the payload at victim machine without victim interaction, can you upload a demo or more doc? 
thanks for sharing you knowledge...
greetings

**Comment by 4w4k3** [comment]
Hi, Sure.
Dropper: https://en.wikipedia.org/wiki/Dropper_(malware)
You can learn about social engineering
Here are a pdf about http://sbisc.ut.ac.ir/wp-content/uploads/2015/10/mitnick.pdf

Umbrella download malware or executable on target and execute it, hiding and opening other file pdf,jpg,docx.... to deceive the user. Basically is this.

For download and exe malware in the target they need execute your umbrella exe generated.

**Comment by devrajashwin** [comment]
same issue .
i really dontunderstand how to use it for further .............................
