### ISSUE TITLE
The file doesnt run after i bind it.

### ISSUE THREAD

**Issue by linuxdaddy** [4w4k3/Umbrella#3]
Hello, im occurring some errors during the file binding. I have installed all depencies, and updated them several times. I create a keylogger with BeeLogger, as we know its the best FUD keylogger maker, after i create the keylogger.exe its size is around 5.3 mb. Then i use ubrella to bind it with an actual Docx file, and like i said during process i get several errors and when the file is ready, when i try to run it, it doesnt work. Neither of the files opens, not even the keylogger. Here i have some screenshots that show what happens during the bindings:
![screenshot from 2017-03-13 23-39-17](https://cloud.githubusercontent.com/assets/26394383/23879057/2e122914-084b-11e7-9246-d3d76569a0ee.png)
![screenshot from 2017-03-13 23-39-14](https://cloud.githubusercontent.com/assets/26394383/23879062/323bc158-084b-11e7-8c59-ed3d2dbfab72.png)
Waiting for your response. Much appreciated.

**Comment by 4w4k3** [comment]
If you wait more dont work?

**Comment by linuxdaddy** [comment]
The file is created after those errors, but it has a smaller size(3.7mb)
than the keylogger(5mb). And when i try to run that file on windows it
doesnt open anything. Neither the keylogger proccess neither the docx file.

**Comment by 4w4k3** [comment]
Verify if your apache are running

**Comment by linuxdaddy** [comment]
Yes, everything is running, i tried it again, i get same errors and same output. Tried the output on my other pc and it doesnt open anything.

**Comment by linuxdaddy** [comment]
I fixed the first error by using `apt-get install winbind`. Now the only error left is this microsoft x86_microsoft.VC90.CRT ... ... ... not found. These are the results i get while binding the files: 
![screenshot from 2017-03-15 20-17-52](https://cloud.githubusercontent.com/assets/26394383/23967227/5e46fbe0-09be-11e7-971c-740792c8b488.png)
![screenshot from 2017-03-15 20-17-54](https://cloud.githubusercontent.com/assets/26394383/23967231/5f8a031c-09be-11e7-9ea3-1e700cf24792.png)

**Comment by 4w4k3** [comment]
Try now, reclone amd thanks for notice of fixed error

**Comment by linuxdaddy** [comment]
It still doesnt work, i need to fix this last error aswell.

**Comment by 4w4k3** [comment]
Try now @linuxdaddy

**Comment by linuxdaddy** [comment]
Should i update the Umbrella?

**Comment by 4w4k3** [comment]
Please remove directory and clone again, updated in check dependencies

**Comment by linuxdaddy** [comment]
Okay gonna try right now and reply.

**Comment by linuxdaddy** [comment]
Sadly again same thing, i get the same errors and the same output, which fails when i run on the victim's machine. Nothing at all opens, not even the keylogger proccess.
Again here are the errors i get during the binding of the files:

![screenshot from 2017-03-20 19-27-47](https://cloud.githubusercontent.com/assets/26394383/24115849/faa9292e-0da4-11e7-8f7e-985c4ecb8b9e.png)
![screenshot from 2017-03-20 19-27-51](https://cloud.githubusercontent.com/assets/26394383/24115850/fbf36af6-0da4-11e7-8fb3-c454f4fefa5e.png)

**Comment by 4w4k3** [comment]
These errors are normals of pyinstaller, if you continue the compilation he work?

**Comment by linuxdaddy** [comment]
I get the output file, but when i open it on victim's pc nothing happens,
no proccess opens, so it doesnt work.
When i try only the keylogger, it works like a charm. But the binded file
doesnt work.

**Comment by 4w4k3** [comment]
Try now
