### ISSUE TITLE
Error installing dependencies 

### ISSUE THREAD

**Issue by EinderJam** [4w4k3/Umbrella#4]
Hi,i come here because I encounter errors when I install python and VCforpython.
The "checker.py" script does not install python 2.7 in wine.
I found that the problem was the "wine msiexec /I python2.7.12.msi",I tested this command alone,and I have no results,no error,nothing.
I solved this by downloading a 32bits version of python,and the command works with this file.
However,I can't do the same thing with VCforpython...
It seems to be a problem with wine architecture,have you got an idea to fix it ?
Anyway,thanks for your great projects !

**Comment by 4w4k3** [comment]
I've tried in some distros and worked fine i dont understand what happens in some machine with wine, but i'll try fix it today

**Comment by EinderJam** [comment]
I tried to install it on Kali Linux,with wine preinstalled.I don't know why it happens,but since it worked with a 32bit file,i think that the problem is between file's arch and wine arch...
Thanks for your reply,i hope you'll find !

**Comment by 4w4k3** [comment]
Try now @EinderJam
